spring:
  application:
    name: file-processor
    multithreaded: ${IS_MULTITHREADED:true}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fileprocessor?useSSL=false}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    show-sql: ${SHOW_SQL:true}
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USER:guest}
    password: ${RMQ_PASSWORD:guest}
  servlet:
    multipart:
      max-file-size: ${MAX_UPLOAD_SIZE:-1}
      max-request-size: ${MAX_UPLOAD_REQUEST_SIZE:-1}
security:
  jwt:
    secret: ${JWT_SECRET:2100628d5a6c27d0cf342603f51d19dd404278267fce707dc2b55d2406642b0a}
    expiration: ${JWT_EXPIRATION:600000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
server:
  port: ${SERVER_PORT:5000}
